// js/global/sections/trabalhos/trabalhos-data.js
// dados dos projetos — edite aqui para adicionar ou alterar trabalhos

const TRABALHOS = [
    {
      id: 'proj-01',
      nome: 'Shopping Center Norte',
      categoria: 'Refrigeração Industrial',
      desc: 'Instalação completa de sistema VRF para 42 lojas com controle centralizado e automação total.',
      dados: [
        { label: 'Capacidade', valor: '480.000 BTUs' },
        { label: 'Área',       valor: '12.400 m²'    },
        { label: 'Unidades',   valor: '42 splits'    },
        { label: 'Prazo',      valor: '8 meses'      },
      ],
      cor: 0x0055cc,
      corHex: '#0055cc',
      icone: 'fa-building',
    },
    {
      id: 'proj-02',
      nome: 'Frigorífico BovFrio',
      categoria: 'Câmara Fria',
      desc: 'Projeto e instalação de câmaras frigoríficas de resfriamento e congelamento para armazenamento de 800 toneladas.',
      dados: [
        { label: 'Temperatura', valor: '-18°C a +4°C' },
        { label: 'Capacidade',  valor: '800 toneladas' },
        { label: 'Câmaras',     valor: '6 unidades'   },
        { label: 'Prazo',       valor: '5 meses'      },
      ],
      cor: 0x006688,
      corHex: '#006688',
      icone: 'fa-snowflake',
    },
    {
      id: 'proj-03',
      nome: 'Hospital São Lucas',
      categoria: 'Ar Condicionado Central',
      desc: 'Sistema de climatização hospitalar com controle de pressão positiva e negativa em UTIs e salas cirúrgicas.',
      dados: [
        { label: 'Capacidade', valor: '320.000 BTUs'  },
        { label: 'Ambientes',  valor: '180 salas'     },
        { label: 'Tipo',       valor: 'VRF + Chiller' },
        { label: 'Prazo',      valor: '12 meses'      },
      ],
      cor: 0x004477,
      corHex: '#004477',
      icone: 'fa-hospital',
    },
    {
      id: 'proj-04',
      nome: 'Galpão LogFrio',
      categoria: 'Refrigeração Industrial',
      desc: 'Sistema de refrigeração para galpão logístico com controle automatizado de temperatura por zonas.',
      dados: [
        { label: 'Área',     valor: '8.200 m²'    },
        { label: 'Zonas',    valor: '4 setores'   },
        { label: 'Controle', valor: 'Automatizado' },
        { label: 'Prazo',    valor: '4 meses'     },
      ],
      cor: 0x003355,
      corHex: '#003355',
      icone: 'fa-warehouse',
    },
    {
      id: 'proj-05',
      nome: 'Rede FrezFresh',
      categoria: 'Câmara Fria + Ar Condicionado',
      desc: 'Padronização e instalação de sistemas de refrigeração e climatização em 12 unidades da rede.',
      dados: [
        { label: 'Unidades',   valor: '12 lojas'    },
        { label: 'Área total', valor: '18.000 m²'   },
        { label: 'Ilhas frio', valor: '240 und.'    },
        { label: 'Prazo',      valor: '10 meses'    },
      ],
      cor: 0x005577,
      corHex: '#005577',
      icone: 'fa-store',
    },
    {
      id: 'proj-06',
      nome: 'Data Center TechCloud',
      categoria: 'Refrigeração de Precisão',
      desc: 'Climatização de precisão para data center com redundância N+1 e monitoramento 24/7.',
      dados: [
        { label: 'Carga',       valor: '1.2 MW' },
        { label: 'PUE alvo',    valor: '1.4'    },
        { label: 'Redundância', valor: 'N+1'    },
        { label: 'Prazo',       valor: '7 meses'},
      ],
      cor: 0x002244,
      corHex: '#002244',
      icone: 'fa-server',
    },
  ];